<?php

use ErickComp\LivewireDataTable\DataTable;
use ErickComp\LivewireDataTable\DataTable\CustomRenderedColumn;
use ErickComp\LivewireDataTable\DataTable\DataColumn;
use ErickComp\LivewireDataTable\Livewire\LwDataTable;
use Illuminate\View\ComponentAttributeBag;
use Livewire\Livewire;

function viewDataColumn(string $title, string $dataField): DataColumn
{
    return DataColumn::fromComponentAttributeBag(new ComponentAttributeBag([
        'title' => $title,
        'data-field' => $dataField,
    ]));
}

// --- Dynamic view data ---

it('passes dynamic view data to custom column renderers', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
        dynamicViewData: ['baseUrl' => 'https://example.com'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(CustomRenderedColumn::fromComponentAttributeBag(
        new ComponentAttributeBag(['title' => 'Link', 'data-field' => 'id']),
        customRendererCode: '<a href="{{ $baseUrl }}/{{ $__row[\'id\'] }}">View</a>',
    ));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSeeHtml('https://example.com/1');
});

it('passes dynamic view data to footer renderer', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product', 'price' => 99]]),
        paginationView: 'bootstrap',
        dynamicViewData: ['currency' => 'USD'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(viewDataColumn('Price', 'price'));

    $dataTable->setFooter(
        new ComponentAttributeBag(),
        '<tr><td colspan="2">Currency: {{ $currency }}</td></tr>',
    );

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('Currency: USD');
});

it('does not allow dynamic view data to override internal variables', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 42, 'name' => 'Real Product']]),
        paginationView: 'bootstrap',
        dynamicViewData: ['__row' => ['id' => 999, 'name' => 'Fake Product']],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(CustomRenderedColumn::fromComponentAttributeBag(
        new ComponentAttributeBag(['title' => 'ID', 'data-field' => 'id']),
        customRendererCode: '{{ $__row[\'id\'] }}',
    ));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('42')
        ->assertDontSee('999');
});

it('works with no view data by default', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('Product');
});

it('passes dynamic view data with multiple values', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'laptop']]),
        paginationView: 'bootstrap',
        dynamicViewData: ['prefix' => 'ITEM', 'separator' => '-'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(CustomRenderedColumn::fromComponentAttributeBag(
        new ComponentAttributeBag(['title' => 'Code', 'data-field' => 'id']),
        customRendererCode: '{{ $prefix }}{{ $separator }}{{ $__row[\'id\'] }}',
    ));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('ITEM-1');
});

// --- Static view data ---

it('passes static view data to custom column renderers', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
        staticViewData: ['appName' => 'MyApp'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(CustomRenderedColumn::fromComponentAttributeBag(
        new ComponentAttributeBag(['title' => 'App', 'data-field' => 'id']),
        customRendererCode: '{{ $appName }}',
    ));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('MyApp');
});

it('passes static view data to footer renderer', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
        staticViewData: ['footerNote' => 'Generated by system'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->setFooter(
        new ComponentAttributeBag(),
        '<tr><td>{{ $footerNote }}</td></tr>',
    );

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('Generated by system');
});

// --- Merging behavior ---

it('merges static and dynamic view data with dynamic taking precedence', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
        staticViewData: ['label' => 'static-value', 'shared' => 'from-static'],
        dynamicViewData: ['label' => 'dynamic-value'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));
    $dataTable->columns->push(CustomRenderedColumn::fromComponentAttributeBag(
        new ComponentAttributeBag(['title' => 'Info', 'data-field' => 'id']),
        customRendererCode: '{{ $label }} | {{ $shared }}',
    ));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    $component->assertSee('dynamic-value | from-static');
});

it('does not send static view data over the wire', function () {
    $dataTable = new DataTable(
        dataSrc: collect([['id' => 1, 'name' => 'Product']]),
        paginationView: 'bootstrap',
        staticViewData: ['config' => 'server-only'],
    );

    $dataTable->columns->push(viewDataColumn('Name', 'name'));

    $component = Livewire::test(LwDataTable::class, ['data-table' => $dataTable]);

    expect($component->get('vd'))->toBe('');
});
